#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
#    healthcheck:
#      enabled: true

spring:
  #  security:
  #    user:
  #      name: admin
  #      password: admin
  #  cloud:
  #    config:
  #      uri: http://localhost:8888
  application:
    name: dossier-services

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"