apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: document-services
spec:
  selector:
    matchLabels:
      app: document-services
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: document-services
    spec:
      containers:
        - name: document-services
          image: wageurts/document-services:0.0.2-SNAPSHOT
          ports:
            - containerPort: 9002