apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dossier-services-deployment
spec:
  selector:
    matchLabels:
      app: dossier-services
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dossier-services
    spec:
      containers:
        - name: dossier-services
          image: wageurts/dossier-services:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9001