eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true


spring:
  application:
    name: util-services
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true

server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: "*"
